swagger: "2.0"
info:
  description: "This is the first version mobile api documentation. You can find out more about Swagger at [http://swagger.io](http://swagger.io)."
  version: "1.0.5"
  title: "GTT"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
basePath: "/api/mobile/v1"
tags:
  - name: "auth"
    description: "Authentication operations"
  - name: "tour"
    description: "Tour operations"
schemes:
  - "https"
  - "http"
parameters:
  HeaderAppVersion:
    name: "appversion"
    type: string
    in: header
    required: false
  HeaderDeviceOs:
    name: "deviceos"
    type: string
    in: header
    required: false
paths:
  /auth/login:
    post:
      tags:
        - "auth"
      summary: "Logs users into the system"
      description: ""
      operationId: "login"
      consumes:
        - "application/x-www-form-urlencoded"
      produces:
        - "application/json"
      parameters:
        - name: "email"
          in: "formData"
          description: "User email"
          required: true
          type: "string"
        - name: "password"
          in: "formData"
          description: "User password"
          required: true
          type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            "$ref": "#/definitions/ApiResponse"
  /auth/register:
    post:
      tags:
        - "auth"
      summary: "Register users into the system"
      description: ""
      operationId: "register"
      consumes:
        - "application/x-www-form-urlencoded"
      produces:
        - "application/json"
      parameters:
        - name: "name"
          in: "formData"
          description: "User name"
          required: true
          type: "string"
        - name: "email"
          in: "formData"
          description: "User email"
          required: true
          type: "string"
        - name: "password"
          in: "formData"
          description: "User password"
          required: true
          type: "string"
        - name: "password_confirmation"
          in: "formData"
          description: "User password(Again)"
          required: true
          type: "string"
      responses:
        "201":
          description: "successful operation"
          schema:
            "$ref": "#/definitions/ApiResponse"
  /tours:
    get:
      tags:
        - "tour"
      summary: "List tours"
      description: ""
      operationId: "tours-index"
      consumes:
        - "application/x-www-form-urlencoded"
      produces:
        - "application/json"
      parameters:
        - name: "page"
          in: "query"
          description: "Page"
          required: false
          type: "integer"
      security:
        - JWT: []
      responses:
        "200":
          description: "successful operation"
          schema:
            "$ref": "#/definitions/ApiResponse"
    post:
      tags:
        - "tour"
      summary: "Add tours"
      description: ""
      operationId: "tours-store"
      consumes:
        - "application/x-www-form-urlencoded"
      produces:
        - "application/json"
      parameters:
        - name: "name"
          in: "formData"
          description: "Tour name"
          required: true
          type: "string"
        - name: "description"
          in: "formData"
          description: "Tour description"
          required: true
          type: "string"
        - name: "location"
          in: "formData"
          description: "Tour location"
          required: true
          type: "string"
        - name: "starts_at"
          in: "formData"
          description: "Tour start date(YYYY-MM-DD H:i:s)"
          required: true
          type: "string"
        - name: "ends_at"
          in: "formData"
          description: "Tour end date(YYYY-MM-DD H:i:s)"
          required: true
          type: "string"
      security:
        - JWT: []
      responses:
        "200":
          description: "successful operation"
          schema:
            "$ref": "#/definitions/ApiResponse"
definitions:
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      status:
        type: "boolean"
      message:
        type: "string"
      data:
        type: "object"
      meta:
        type: "object"
externalDocs:
  description: "Find out more about Swagger"
  url: "https://swagger.io"
securityDefinitions:
  JWT:
    type: "apiKey"
    in: "header"
    name: "Authorization"
